### ISSUE TITLE
telegram.error.BadRequest: Failed to send message #4 with the error message "failed to get http url content"

### ISSUE THREAD

**Issue by Nachtalb** [Nachtalb/reverse_image_search_bot#20]
```python 
Failed to send message #4 with the error message "failed to get http url content"
Traceback (most recent call last):
  File "/home/web_server/telegram/reverse_image_search_bot/reverse_image_search_bot/commands.py", line 398, in _best_match_search
    message.reply_media_group(
  File "/home/web_server/.pyenv/versions/reverse_image_search_bot/lib/python3.10/site-packages/telegram/message.py", line 998, in reply_media_group
    return self.bot.send_media_group(
  File "/home/web_server/.pyenv/versions/reverse_image_search_bot/lib/python3.10/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/web_server/.pyenv/versions/reverse_image_search_bot/lib/python3.10/site-packages/telegram/bot.py", line 1587, in send_media_group
    result = self._post('sendMediaGroup', data, timeout=timeout, api_kwargs=api_kwargs)
  File "/home/web_server/.pyenv/versions/reverse_image_search_bot/lib/python3.10/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/home/web_server/.pyenv/versions/reverse_image_search_bot/lib/python3.10/site-packages/telegram/utils/request.py", line 359, in post
    result = self._request_wrapper('POST', url, fields=data, **urlopen_kwargs)
  File "/home/web_server/.pyenv/versions/reverse_image_search_bot/lib/python3.10/site-packages/telegram/utils/request.py", line 279, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Failed to send message #4 with the error message "failed to get http url content"
```

**Comment by Nachtalb** [comment]
Not relevant anymore due to rewrite: https://github.com/Nachtalb/reverse_image_search_bot/pull/22
